### ISSUE TITLE
Validni broj racuna ne prolazi validaciju

### ISSUE THREAD

**Issue by ivansenic** [ArtBIT/ips-qr-code#12]
Imam broj racuna `115038169338697697` koji ne prolazi validaciju. 

Funkcija `cdigit.mod97_10.compute` vraca ovde `00` umesto `97`, jel ste sigurni da se koristi ispravan algoritam. Na https://sr.wikipedia.org/wiki/Struktura_broja_teku%C4%87eg_ra%C4%8Duna piše da je standard  `ISO 7064, МОО111- 97` a na `cdigit`  za `mod97_10` da je `ISO/IEC 7064, MOD 97-10 | mod97_10`? Možda je bug kod njih?

Voleo bih da pomognem ako mogu.

**Comment by ArtBIT** [comment]
Pozdrav Ivane,

Napisao sam svoju funkciju za validaciju, i sada taj broj racuna prolazi.
Pokušajte da instalirate verziju 1.0.5

Pozdrav,
Djordje

**Comment by ivansenic** [comment]
@ArtBIT Sjajno.. Ja sam napisao isto dosta jednostavniju varijantu sa `BigInt`:

```
const validateBankovniRacun = input => {
    // https://sr.wikipedia.org/wiki/Struktura_broja_teku%C4%87eg_ra%C4%8Duna
    // Kontrolni broj se sastoji od dve cifre, koje se izračunavaju na po međunarodnom standardu ISO 7064, МОО111- 97
    // kontr. br.=98 - mod(2520000000123456*100,97)


    try {
        // we need to use big int, to avoid overflow
        const racunStr = input.slice(0,-2);
        const racun = BigInt(racunStr);
        const leftover = racun * 100n % 97n;
        const expected = 98n - leftover;

        // for control we can use standard int
        const controlStr = input.slice(-2);
        const control = parseInt(controlStr);

        // final comparison must be of same types
        // thus, parse BigInt to number
        return parseInt(expected) === control;
    } catch (e) {
        return false;
    }
}
```

Ali svakako cu testirati tvoje resenje i zatvoriti issue ako se potvrdi da je OK.

**Comment by ivansenic** [comment]
Sve OK.
