### ISSUE TITLE
Poziv na broj ne prolazi validaciju

### ISSUE THREAD

**Issue by jovanivanovic** [ArtBIT/ips-qr-code#15]
Pozdrav, kada se unese poziv na broj po modelu 97 koji sadrzi slova, ne uspeva da prodje validaciju jer ignorise slova umesto da ih konvertuje u odgovarajuci dvocifren broj. Ispod je tabela sa slovima i odgovarajucom brojevnom interpretacijom.

| Slovo | Broj || Slovo | Broj || Slovo | Broj |
| --- | --- | --- | --- | --- | --- | --- | --- |
| A | 10 || B | 11 || C | 12 |
| D | 13 || E | 14 || F | 15 |
| G | 16 || H | 17 || I | 18 |
| J | 19 || K | 20 || L | 21 |
| M | 22 || N | 23 || O | 24 |
| P | 25 || Q | 26 || R | 27 |
| S | 28 || T | 29 || U | 30 |
| V | 31 || W | 32 || X | 33 |
| Y | 34 || Z | 35 ||   |    |

**Comment by ArtBIT** [comment]
Hvala, ispravljeno.
