### ISSUE TITLE
Greska u jednokratnoj sifri

### ISSUE THREAD

**Issue by avionbg** [ArtBIT/ips-qr-code#19]
Deluje da imate gresku u kodu - vezano za jednokratnu sifru.
Naime po dostupnoj dokumentaciji trebalo bi da bude JS a ne JF.
Link prema dokumentu sa definicijom polja:
[Kesirana strana](https://webcache.googleusercontent.com/search?q=cache:YNP6oWzpma0J:https://www.nbs.rs/export/sites/NBS_site/documents/propisi/propisi-ps/instant_transfer_2019_p_p.docx&cd=4&hl=en&ct=clnk&gl=rs)
[NBS dokument](https://www.nbs.rs/export/sites/NBS_site/documents/propisi/propisi-ps/instant_transfer_2019_p_p.docx)

**Comment by ArtBIT** [comment]
Ispravljeno. Hvala.
